// Generated by CoffeeScript 1.9.1
var resumeGame, setAsteroidAngularVelocity, setAsteroidDamping, setAsteroidDensity, setAsteroidFriction, setAsteroidLinearVelocity, setAsteroidRestitution, setBackground, setBulletDamping, setBulletDensity, setBulletFriction, setBulletLinearVelocity, setBulletRestitution, setPlayMusic, setPlaySfx, setProfiler, setSpaceshipDamping, setSpaceshipDensity, setSpaceshipFriction, setSpaceshipRestitution;

resumeGame = function() {
  Cocoon.WebView.hide();
  Cocoon.Touch.enable();
  Cocoon.App.forward("asteroids.pause();");
};


/**
Game Options
 */

setProfiler = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('profiler', '" + value + "');");
  return value;
};

setBackground = function(value) {
  if (value === 1) {
    Cocoon.App.forwardAsync("asteroids.set('background', 1);");
  } else {
    Cocoon.App.forwardAsync("asteroids.set('background', 0);");
  }
};

setPlayMusic = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('playMusic', " + value + ");");
  return value;
};

setPlaySfx = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('playSfx', " + value + ");");
  return value;
};


/**
Asteroids
 */

setAsteroidDensity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidDensity', " + value + ");");
  return value;
};

setAsteroidFriction = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidFriction', " + value + ");");
  return value;
};

setAsteroidRestitution = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidRestitution', " + value + ");");
  return value;
};

setAsteroidDamping = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidDamping', " + value + ");");
  return value;
};

setAsteroidLinearVelocity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidLinearVelocity', " + value + ");");
  return value;
};

setAsteroidAngularVelocity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('asteroidAngularVelocity', " + value + ");");
  return value;
};


/**
Spaceships
 */

setSpaceshipDensity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('spaceshipDensity', " + value + ");");
  return value;
};

setSpaceshipFriction = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('spaceshipFriction', " + value + ");");
  return value;
};

setSpaceshipRestitution = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('spaceshipRestitution', " + value + ");");
  return value;
};

setSpaceshipDamping = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('spaceshipDamping', " + value + ");");
  return value;
};


/**
Bullets
 */

setBulletDensity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('bulletDensity', " + value + ");");
  return value;
};

setBulletFriction = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('bulletFriction', " + value + ");");
  return value;
};

setBulletRestitution = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('bulletRestitution', " + value + ");");
  return value;
};

setBulletDamping = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('bulletDamping', " + value + ");");
  return value;
};

setBulletLinearVelocity = function(value) {
  Cocoon.App.forwardAsync("asteroids.set('bulletLinearVelocity', " + value + ");");
  return value;
};

window.addEventListener("load", function() {
  var e;
  $("body").css("visibility", "visible");
  try {
    Cocoon.App.forwardAsync("asteroids.get('profiler');", function(value) {
      $("#profiler").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('background');", function(value) {
      if (value === 0) {
        $("#blueBgd").attr("checked", "checked");
      } else {
        $("#starBgd").attr("checked", "checked");
      }
      $("input[type=radio]").checkboxradio("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('playMusic');", function(value) {
      $("#playMusic").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('playSfx');", function(value) {
      $("#playSfx").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidDensity');", function(value) {
      $("#asteroidDensity").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidFriction');", function(value) {
      $("#asteroidFriction").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidRestitution');", function(value) {
      $("#asteroidRestitution").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidDamping');", function(value) {
      $("#asteroidDamping").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidLinearVelocity');", function(value) {
      $("#asteroidLinearVelocity").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('asteroidAngularVelocity');", function(value) {
      $("#asteroidAngularVelocity").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('spaceshipDensity');", function(value) {
      $("#spaceshipDensity").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('spaceshipFriction');", function(value) {
      $("#spaceshipFriction").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('spaceshipRestitution');", function(value) {
      $("#spaceshipRestitution").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('spaceshipDamping');", function(value) {
      $("#spaceshipDamping").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('bulletDensity');", function(value) {
      $("#bulletDensity").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('bulletFriction');", function(value) {
      $("#bulletFriction").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('bulletRestitution');", function(value) {
      $("#bulletRestitution").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('bulletDamping');", function(value) {
      $("#bulletDamping").val(value).slider("refresh");
    });
    Cocoon.App.forwardAsync("asteroids.get('bulletLinearVelocity');", function(value) {
      $("#bulletLinearVelocity").val(value).slider("refresh");
    });
  } catch (_error) {
    e = _error;
    console.log(e.toString());
  } finally {
    Cocoon.Touch.disable();
  }
});

//# sourceMappingURL=settings.js.map
